name: Test Style Dictionary PL

on: 
  pull_request:
    branches: [main]
    types: [closed]
  issue_comment:
    branches: [main]
    types: [edited, created]
jobs:
  install_style_dictionary:
    name: Install Style Dictionary
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Install Dependencies
        run: npm ci
      - name: Install Style Dictionary
        run: npm install -g style-dictionary
      - name: Build Style Dictionary Json
        run: cd examples/complete/ && style-dictionary build
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Generated Dictionary Auto-Commit
          branch: main
      - name: Publish library to artifactory
        run: cd examples/complete/android/ && ./gradlew artifactoryPublish
